### ISSUE TITLE
OSError: [Errno 8] Exec format error when "qira /bin/ls /"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BoiBetter/qira#2]
```
What steps will reproduce the problem?
1. Launch qira /bin/ls /

Gets me:

*** /root/qira/qemu/qira-i386 -strace -D /dev/null -d in_asm -singlestep 
/bin/ls /
Traceback (most recent call last):
  File "/usr/local/bin/qira", line 42, in <module>
    program.execqira()
  File "/root/qira/middleware/qira_program.py", line 156, in execqira
    os.execvp(self.qirabinary, eargs)
  File "/usr/lib/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 368, in _execvpe
    func(file, *argrest)
OSError: [Errno 8] Exec format error

What version of the product are you using? On what operating system?

$ uname -a
Linux ean32 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:42:40 UTC 
2014 i686 i686 i386 GNU/Linux

https://qira.googlecode.com/git/releases/qira-0.6.tar.xz


```

Original issue reported on code.google.com by `noone...@gmail.com` on 30 Jul 2014 at 6:12

**Comment by GoogleCodeExporter** [comment]
```
QIRA isn't currently supported on i386, x86-64 is required.
```

Original comment by `geo...@google.com` on 30 Jul 2014 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
Had the same problem, we found out that I was running 32bit linux on 64bit 
kernel -_- Maybe have a look at it as well.
```

Original comment by `faekko...@googlemail.com` on 30 Jul 2014 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
QIRA falls back to building QEMU if the distributed binaries don't run, tested 
on precise32, so I consider this issue fixed.
```

Original comment by `geo...@gmail.com` on 2 Aug 2014 at 6:59
- Changed state: **Fixed**
