### ISSUE TITLE
does not check version >=0.3.2 of greenlet when installing, fails to run.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BoiBetter/qira#4]
```
What steps will reproduce the problem?

1. Install qira using ./install.sh
2. recieve no errors during installation
3. run qira

root@sid:/home/vmuser/qira/qira# qira
Traceback (most recent call last):
  File "/usr/local/bin/qira", line 12, in <module>
    import qira_webserver
  File "/home/vmuser/qira/qira/middleware/qira_webserver.py", line 17, in <module>
    from flask.ext.socketio import SocketIO, emit
  File "/usr/local/lib/python2.7/dist-packages/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 1, in <module>
    from gevent import monkey
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 14, in <module>
    You can get a newer version of greenlet from http://pypi.python.org/pypi/greenlet/''' % (greenlet_version, ))
ImportError: Your version of greenlet (0.3.1) is too old (required >= 0.3.2)
             You can get a newer version of greenlet from http://pypi.python.org/pypi/greenlet/


root@sid:/home/vmuser/qira/qira# pip install greenlet --upgrade
Downloading/unpacking greenlet from 
https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.2.zip#md5=580a8a
5e833351f7abdaedb1a877f7ac
  Downloading greenlet-0.4.2.zip (74kB): 74kB downloaded
  Running setup.py (path:/tmp/pip_build_root/greenlet/setup.py) egg_info for package greenlet

Installing collected packages: greenlet
  Found existing installation: greenlet 0.3.1
    Uninstalling greenlet:
      Successfully uninstalled greenlet
  Running setup.py install for greenlet
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts -I/usr/include/python2.7 -c /tmp/tmpFqMHdP/simple.c -o /tmp/tmpFqMHdP/tmp/tmpFqMHdP/simple.o
    /tmp/tmpFqMHdP/simple.c:1:6: warning: function declaration isnât a prototype [-Wstrict-prototypes]
    building 'greenlet' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/greenlet.o -o build/lib.linux-x86_64-2.7/greenlet.so
    Linking /tmp/pip_build_root/greenlet/build/lib.linux-x86_64-2.7/greenlet.so to /tmp/pip_build_root/greenlet/greenlet.so

Successfully installed greenlet
Cleaning up...
root@sid:/home/vmuser/qira/qira# qira
usage: qira [-h] [-s] [-t] [--flush-cache] [--dwarf] [--cda]
            binary [args [args ...]]
qira: error: too few arguments

```

Original issue reported on code.google.com by `Godo...@gmail.com` on 2 Aug 2014 at 1:50

**Comment by GoogleCodeExporter** [comment]
```
Added --upgrade to the pip command in install.
```

Original comment by `geo...@gmail.com` on 2 Aug 2014 at 6:41

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report! Closing bug.
```

Original comment by `geo...@gmail.com` on 2 Aug 2014 at 6:42
- Changed state: **Fixed**
